spring:
  application:
    name: shopwise
  datasource:
    url: jdbc:postgresql://localhost:5432/shopwise
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

#  domain/        -> Hiçbir şeye bağımlı değil
#  application/   -> Sadece domain'e bağımlı
#  infrastructure/-> application + domain'e bağımlı
#  api/           -> application'a bağımlı